### ISSUE TITLE
Where are sources of the server?

### ISSUE THREAD

**Issue by valerio-vaccaro** [chainpoint/chainpoint-binary#1]
I'm interested in testing Chainpoint service but unfortunately I can not see the sources of the server part of this protocol. 
I thought this part was open source also, am I wrong?

**Comment by grempe** [comment]
Hello Valerio

We'll have more to announce on that topic soon. Please stay tuned.

Congrats on joining Eternity Wall!

Cheers

**Comment by grempe** [comment]
Closing, as not an issue with chainpoint-binary per se.
